MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"

  ####step2
  WEIGHT: "/media/cgz/新加卷/XWJ/NEU/source_model/0-3/model_7000.pth"
  SOURCE_WEIGHT: "/media/cgz/新加卷/XWJ/NEU/source_model/0-3/model_7000.pth"
  FTN: "/media/cgz/新加卷/XWJ/NEU/source_model/0-3/model_7000.pth"
  CTN: "/media/cgz/新加卷/XWJ/NEU/source_model/4-6/model_4500.pth"

  BACKBONE:
    CONV_BODY: "R-50-C4"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
  RPN:
    USE_FPN: False
    ANCHOR_STRIDE: (16,)
    PRE_NMS_TOP_N_TRAIN: 12000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: False
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.0625,)
    POOLER_SAMPLING_RATIO: 0
    FEATURE_EXTRACTOR: "ResNet50Conv5ROIFeatureExtractor"
    PREDICTOR: "FastRCNNPredictor"
    #STEP2
    NUM_CLASSES: 7 # total classes : 20 + 1
    NAME_OLD_CLASSES: ["crazing", "inclusion", "patches",]
    NAME_NEW_CLASSES: ["pitted_surface","rolled-in_scale","scratches"]
    NAME_EXCLUDED_CLASSES: []
DATASETS:
  TRAIN: ("neu_train",)
  TEST: ("neu_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 0
SOLVER:
  BASE_LR: 0.0004 # start learning rate

  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1  # learning rate decay
  STEPS: (7500,)
  MAX_ITER: 10000 #2500  # number of iteration
  CHECKPOINT_PERIOD: 500  # number of iteration to generate check point
  IMS_PER_BATCH: 4 # number of images per batch
  MOMENTUM: 0.9
TEST: # testing strategy
  IMS_PER_BATCH: 4 # number of images per batch

#NAME: 10-10_LR005_BS4_ROI
OUTPUT_DIR: "/media/cgz/新加卷/XWJ/NEU/ADT-ILDFD" # path to store the result
TENSORBOARD_DIR: "output/" # path to store tensorboard info
#DTYPE: "float16"#